### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by ellispatrick** [drighelli/SpatialExperiment#139] opened 2023-08-21 23:50 UTC
Hi,

We have been trying to reduce the number of dependencies for some of our packages. Looking in dependency trees, a significant proportion of SpatialExperiment's dependencies come drop DropletUtils. It seems like read10xCounts() is only used in the examples and vignette, perhaps 1) maybe it doesn't need to be used at all or 2) add it to Suggests? I'm unsure about Bioconductor standards, but this would align with Hadley's recommendations.

"Suggests: your package can use these packages, but doesn’t require them. You might use suggested packages for example datasets, to run tests, build vignettes, or maybe there’s only one function that needs the package."

https://r-pkgs.org/dependencies-mindset-background.html#sec-dependencies-imports-vs-suggests

Thanks,
Ellis

**Comment by lmweber** [comment] 2023-08-22 15:38
Hi @ellispatrick , thanks for this suggestion.

Yes, `DropletUtils` is mainly used within the `read10xVisium()` function, and also in some of the examples.

It may make sense to move this to `Suggests:` instead of `Imports:` so it is not installed automatically -- although then maybe we also should include a message when using `read10xVisium()` so that beginner users know what the problem is if they get an error when using `read10xVisium()` (i.e. something like "this function requires DropletUtils to be installed"). Otherwise people who are new-ish to R may be confused if they just installed the package and assumed it will automatically install all required dependencies. I believe there is a similar issue with `uwot` as a dependency in `scran`/`scater`.

Thanks for the link above to the section in the R Packages book -- some useful details / recommendations there about choosing `Imports:` vs. `Suggests:` too.

I'll assign this issue to me for now and we can consider some more.

**Comment by drighelli** [comment] 2023-08-29 10:05
hello here,

thanks for opening this issue. 
This is a known problem that we're discussing in some other packages with other developers like Aaron and Marcel.

One solution is to move the `read10xVisium` function to the `TENxIO` package which seems to be the elected package for all the 10x import functions.

See also https://github.com/waldronlab/TENxIO/issues/3

In the meantime, I think the `Suggests:` solution would be a very nice workaround.

Dario

**Comment by lmweber** [comment] 2023-09-02 14:18
Hi @ellispatrick @drighelli , we just pushed this change to Bioc-devel in this pull request: https://github.com/drighelli/SpatialExperiment/pull/140

Thanks again for the suggestion.

Let's wait for it to go through the Bioc build system over the next couple of days, and then we can confirm the new lower number of dependencies and close this issue if we are happy with it.

**Comment by lmweber** [comment] 2023-09-11 01:55
I checked and this update has now reduced the number of dependencies from 100 to 73 in Bioc-devel, so I think this is a good improvement! I'll close the issue. Thank you!

**Closed as completed by lmweber** 2023-09-11 01:55 UTC
