### ISSUE TITLE
Request that images of `ve` example data not rely on having this repo cloned in a specific spot.

### ISSUE THREAD

**Issue by dtm2451** [drighelli/SpatialExperiment#28] opened 2021-01-28 05:01 UTC
I don't believe that the current method would work on the Bioc build system anyway, so I bet you were planning to do this already.

1. One option would be to reduce the resolution of the images enough that they can be stored in the object as grobs.

2. Another, re @LTLA, would be to add the images and other files underlying `ve` to the `DropletTestFiles` package, and then have a function in `DropletTestFiles` that retrieves & constructs the object.

Perhaps 1 is better for use in function documentation examples, whereas 2 may be better for the vignette only? Then images can be pretty in the vignette, but users could work through function documentation without needing to install `DropletTestFiles` nor needing to rely on ExperimentHub/AWS in countries where AWS retrieval is spotty.

**Comment by drighelli** [comment] 2021-01-28 10:17
the problem with the ve data was my fault, we already provided 10x Visium low-resolution images with the package.

I think it's better this way to avoid as much dependencies as possible.

Thanks for pointing this out and for the suggestions!

**Comment by drighelli** [comment] 2021-01-28 10:19
oh the problem is fixed in version 1.1.421, I've also pushed this to the bioconductor upstream, in a few days (I suppose) you'd be able to install it from there.

**Closed by drighelli** 2021-01-28 10:19 UTC
